# Generated by Django 5.2.7 on 2025-11-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntryLineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=False)),
                ('power', models.CharField(choices=[('200', '200'), ('400', '400'), ('600', '600'), ('800', '800')], default='600', max_length=3)),
                ('weather', models.CharField(max_length=20)),
                ('morning_data_charge', models.IntegerField()),
                ('morning_data_price', models.FloatField()),
                ('afternoon_data_charge', models.IntegerField()),
                ('afternoon_data_price', models.FloatField()),
                ('evening_data_charge', models.IntegerField()),
                ('evening_data_price', models.FloatField()),
                ('full_day_power', models.FloatField()),
                ('full_day_cost', models.FloatField()),
                ('power_tariff', models.FloatField()),
            ],
        ),
    ]
