# Generated by Django 5.2.7 on 2025-11-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='afternoon_data_charge',
            field=models.IntegerField(verbose_name='Денний рівень заряду'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='afternoon_data_price',
            field=models.FloatField(verbose_name='Вартість використаної енергії на день'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='date',
            field=models.DateField(default=False, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='evening_data_charge',
            field=models.IntegerField(verbose_name='Вечірній рівень заряду'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='evening_data_price',
            field=models.FloatField(verbose_name='Вартість використаної енергії на вечір'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='full_day_cost',
            field=models.FloatField(blank=True, verbose_name='Вартість виробленої енергії за день'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='full_day_power',
            field=models.FloatField(blank=True, verbose_name='Вироблена потужність за день'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='morning_data_charge',
            field=models.IntegerField(verbose_name='Ранковий рівень заряду'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='morning_data_price',
            field=models.FloatField(verbose_name='Вартість використаної енергії на ранок'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='power',
            field=models.CharField(choices=[('200', '200'), ('400', '400'), ('600', '600'), ('800', '800')], default='600', max_length=3, verbose_name='Потужність системи'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='power_tariff',
            field=models.FloatField(verbose_name='Вартість за Кв'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='weather',
            field=models.CharField(max_length=20, verbose_name='Погода'),
        ),
    ]
