# Generated by Django 5.2.7 on 2025-11-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_dataentrylinemodel_afternoon_data_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='power_tariff',
            field=models.FloatField(default='4.32', verbose_name='Вартість за Кв'),
        ),
    ]
