# Generated by Django 5.2.7 on 2025-11-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_dataentrylinemodel_power_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='full_day_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Вартість виробленої енергії за день'),
        ),
    ]
