# Generated by Django 5.2.7 on 2025-11-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_dataentrylinemodel_afternoon_data_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='afternoon_data_charge',
            field=models.IntegerField(default=0, verbose_name='Денний рівень заряду'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='afternoon_data_price',
            field=models.FloatField(default=0, verbose_name='Вартість використаної енергії на день'),
        ),
    ]
