# Generated by Django 5.2.7 on 2025-11-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_alter_dataentrylinemodel_afternoon_data_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='weather',
            field=models.CharField(max_length=22, verbose_name='Погода'),
        ),
    ]
