# Generated by Django 5.2.7 on 2025-11-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_dataentrylinemodel_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTariffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_tariff', models.FloatField(default=4.32, verbose_name='Актуальна вартість за Кв')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Актуальний Тариф',
                'verbose_name_plural': 'Актуальний Тариф',
            },
        ),
        migrations.AlterModelOptions(
            name='dataentrylinemodel',
            options={'ordering': ['-date'], 'verbose_name': 'entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='power_tariff',
            field=models.FloatField(verbose_name='Вартість за Кв'),
        ),
    ]
