# Generated by Django 5.2.7 on 2025-12-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_weathercondition_remove_dataentrylinemodel_weather_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentrylinemodel',
            name='default_day_energy_formula',
            field=models.BooleanField(default=False),
        ),
    ]
