# Generated by Django 5.2.7 on 2026-03-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_dataentrylinemodel_default_day_energy_formula'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherCondition',
            new_name='WeatherConditionModel',
        ),
    ]
