# Generated by Django 6.0.3 on 2026-03-26 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_rename_weathercondition_weatherconditionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarForecastRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Forecast date')),
                ('predicted_kwh', models.FloatField(verbose_name='Forecast (kWh)')),
                ('predicted_savings', models.FloatField(verbose_name='Projected savings (UAH)')),
                ('peak_hour', models.IntegerField(verbose_name='Rush hour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'forecast record',
                'verbose_name_plural': 'Forecasts history',
                'ordering': ['-date'],
            },
        ),
    ]
