# Generated by Django 6.0.3 on 2026-03-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_solarforecastrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('success', 'Success')], default='info', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('msg_type', models.CharField(default='weather', max_length=50)),
                ('event_date', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField(help_text='Celsius')),
                ('cloud_cover', models.IntegerField(help_text='Cloud percentage 0-100')),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('precipitation_prob', models.FloatField(default=0, help_text='Chance of precipitation')),
                ('condition_code', models.CharField(help_text="For example: 'sunny', 'rain'", max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Weather Data Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
