# Generated by Django 6.0.3 on 2026-03-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_systemmessage_weatherdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolarForecastRecord',
            new_name='SolarForecastRecordModel',
        ),
        migrations.RenameModel(
            old_name='WeatherData',
            new_name='WeatherDataModel',
        ),
    ]
