# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 5.2.7 on 2026-05-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_rename_solarforecastrecord_solarforecastrecordmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentrylinemodel',
            name='extra_power',
            field=models.IntegerField(default=0, verbose_name='Приблизна потужність використана на USB'),
        ),
    ]
