# Generated by Django 5.2.7 on 2026-06-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_dataentrylinemodel_extra_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='extra_power',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Приблизна потужність використана на USB'),
        ),
    ]
