# Generated by Django 5.2.7 on 2026-06-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0016_alter_dataentrylinemodel_extra_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarforecastrecordmodel',
            name='sunrise_sunset',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sunrise sunset'),
        ),
    ]
