# Generated by Django 5.2.7 on 2026-06-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0017_solarforecastrecordmodel_sunrise_sunset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarforecastrecordmodel',
            name='sunrise_sunset',
        ),
        migrations.AddField(
            model_name='solarforecastrecordmodel',
            name='sunrise',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Sunrise sunrise'),
        ),
        migrations.AddField(
            model_name='solarforecastrecordmodel',
            name='sunset',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Sunrise sunset'),
        ),
    ]
