# Generated by Django 5.2.7 on 2026-06-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0018_remove_solarforecastrecordmodel_sunrise_sunset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarforecastrecordmodel',
            name='sunrise',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sunrise'),
        ),
        migrations.AlterField(
            model_name='solarforecastrecordmodel',
            name='sunset',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sunset'),
        ),
    ]
