# Generated by Django 5.2.7 on 2026-06-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0019_alter_solarforecastrecordmodel_sunrise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarforecastrecordmodel',
            name='wind_gusts_10m',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wind gusts 10m'),
        ),
        migrations.AddField(
            model_name='solarforecastrecordmodel',
            name='wind_speed_10m',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wind speed 10m'),
        ),
    ]
