# Generated by Django 5.2.7 on 2026-06-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0020_solarforecastrecordmodel_wind_gusts_10m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarforecastrecordmodel',
            name='wind_direction_10m',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wind direction 10m'),
        ),
    ]
