# Generated by Django 5.2.7 on 2026-07-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0021_solarforecastrecordmodel_wind_direction_10m'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeolocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(help_text='Latitude')),
                ('lon', models.FloatField(help_text='Longitude')),
            ],
            options={
                'verbose_name': 'add coordinates',
                'verbose_name_plural': 'Coordinates',
            },
        ),
    ]
