# Generated by Django 5.2.7 on 2026-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0022_geolocationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocationmodel',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='geolocationmodel',
            name='lon',
        ),
        migrations.AddField(
            model_name='geolocationmodel',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude', null=True),
        ),
        migrations.AddField(
            model_name='geolocationmodel',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude', null=True),
        ),
    ]
