# Generated by Django 5.2.7 on 2026-07-03 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0023_remove_geolocationmodel_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelsArrayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the array')),
                ('peak_power_kwp', models.FloatField(verbose_name='Peak power (kWp)')),
                ('area', models.FloatField(verbose_name='Panel(s) area')),
                ('angle', models.FloatField(verbose_name='Panel(s) angle of inclination of the panel')),
                ('azimuth', models.FloatField(verbose_name='Panel(s) azimuth')),
                ('efficiency', models.FloatField(default=0.2, verbose_name='Efficiency of the panel(s) (напр. 0.20)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'panel(s) area',
                'verbose_name_plural': 'panels(s) area',
            },
        ),
    ]
