# Generated by Django 5.2.7 on 2026-07-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0024_panelsarraymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelsarraymodel',
            name='peak_power_kwp',
            field=models.FloatField(blank=True, null=True, verbose_name='Peak power (kWp)'),
        ),
    ]
