# Generated by Django 5.2.7 on 2026-07-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0025_alter_panelsarraymodel_peak_power_kwp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelsarraymodel',
            name='peak_power_kwp',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Peak power (kWp)'),
        ),
    ]
