# Generated by Django 5.2.7 on 2026-07-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0026_alter_panelsarraymodel_peak_power_kwp'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarforecastrecordmodel',
            name='diffuse_radiation',
            field=models.FloatField(blank=True, null=True, verbose_name='Diffuse Radiation'),
        ),
        migrations.AddField(
            model_name='solarforecastrecordmodel',
            name='direct_radiation',
            field=models.FloatField(blank=True, null=True, verbose_name='Direct Radiation'),
        ),
        migrations.AddField(
            model_name='solarforecastrecordmodel',
            name='shortwave_radiation',
            field=models.FloatField(blank=True, null=True, verbose_name='Shortwave Radiation'),
        ),
        migrations.AddField(
            model_name='solarforecastrecordmodel',
            name='surface_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface pressure'),
        ),
    ]
