# Generated by Django 5.2.7 on 2026-07-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0027_solarforecastrecordmodel_diffuse_radiation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdatamodel',
            name='diffuse_radiation',
            field=models.FloatField(blank=True, null=True, verbose_name='Diffuse Radiation'),
        ),
        migrations.AddField(
            model_name='weatherdatamodel',
            name='direct_radiation',
            field=models.FloatField(blank=True, null=True, verbose_name='Direct Radiation'),
        ),
        migrations.AddField(
            model_name='weatherdatamodel',
            name='shortwave_radiation',
            field=models.FloatField(blank=True, null=True, verbose_name='Shortwave Radiation'),
        ),
        migrations.AddField(
            model_name='weatherdatamodel',
            name='surface_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface pressure'),
        ),
        migrations.AddField(
            model_name='weatherdatamodel',
            name='wind_direction_10m',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wind direction 10m'),
        ),
        migrations.AddField(
            model_name='weatherdatamodel',
            name='wind_gusts_10m',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wind gusts 10m'),
        ),
        migrations.AddField(
            model_name='weatherdatamodel',
            name='wind_speed_10m',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wind speed 10m'),
        ),
    ]
