# Generated by Django 5.2.7 on 2026-07-10 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0028_weatherdatamodel_diffuse_radiation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentrylinemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='panelsarraymodel',
            name='efficiency',
            field=models.FloatField(default=0.2, verbose_name='Efficiency of the panel(s)'),
        ),
    ]
