# Generated by Django 5.2.7 on 2026-07-11 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0030_systemeventmodel_systemevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemeventmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'add system event', 'verbose_name_plural': 'System events'},
        ),
        migrations.AddField(
            model_name='systemeventmodel',
            name='category',
            field=models.CharField(choices=[('FORECAST', 'Solar Forecast'), ('REPORT', 'Analytics Report'), ('NOTIFICATION', 'System Notification'), ('WARNING', 'Warning')], default='FORECAST', max_length=20),
        ),
        migrations.AddField(
            model_name='systemeventmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-07-11 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemeventmodel',
            name='event_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='systemeventmodel',
            name='level',
            field=models.CharField(choices=[('SUCC', 'Success'), ('INFO', 'Info'), ('WARN', 'Warn'), ('ERR', 'Error')], default='2026-07-11 13:00:00', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemeventmodel',
            name='payload',
            field=models.JSONField(default=dict, help_text='Complex data'),
        ),
        migrations.AddField(
            model_name='systemeventmodel',
            name='title',
            field=models.CharField(default='Empty title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemeventmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SystemEvent',
        ),
    ]
