# Generated by Django 5.2.7 on 2026-07-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0033_usertimezonemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimezonemodel',
            name='timezone',
            field=models.CharField(default='Europe/Kyiv', max_length=64, verbose_name='Timezone of the user'),
            preserve_default=False,
        ),
    ]
