# Generated by Django 5.2.7 on 2026-07-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0035_usercurrencymodel_userlanguagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercurrencymodel',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='Currency of the user'),
        ),
    ]
