# Generated by Django 5.2.7 on 2026-07-15 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0036_alter_usercurrencymodel_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude', null=True)),
                ('timezone', models.CharField(blank=True, default='', max_length=64, verbose_name='Timezone')),
                ('language', models.CharField(blank=True, default='en', max_length=64, verbose_name='Language')),
                ('currency', models.CharField(blank=True, default='UAH', max_length=3, verbose_name='Currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'Users Settings',
            },
        ),
    ]
