# Generated by Django 5.2.7 on 2026-07-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0037_userprofilesettingsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercurrencymodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlanguagemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertimezonemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='GeolocationModel',
        ),
        migrations.DeleteModel(
            name='UserCurrencyModel',
        ),
        migrations.DeleteModel(
            name='UserLanguageModel',
        ),
        migrations.DeleteModel(
            name='UserTimeZoneModel',
        ),
    ]
