# Generated by Django 5.2.7 on 2026-07-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0038_remove_usercurrencymodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemeventmodel',
            name='isPersistent',
            field=models.BooleanField(default=True),
        ),
    ]
