# Generated by Django 5.2.7 on 2026-07-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0039_systemeventmodel_ispersistent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemeventmodel',
            old_name='isPersistent',
            new_name='is_persistent',
        ),
    ]
