# Generated by Django 5.2.7 on 2026-07-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0040_rename_ispersistent_systemeventmodel_is_persistent'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemeventmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
