# Generated by Django 5.2.7 on 2026-07-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0041_systemeventmodel_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemeventmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='SystemEventModel',
        ),
    ]
