# Generated by Django 5.2.7 on 2026-07-25 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0042_remove_systemeventmodel_user_delete_systemmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeakEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_hour', models.IntegerField()),
                ('status', models.CharField(choices=[('PEAK_START', 'Peak Start'), ('PEAK_END', 'Peak End')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Peak generation event',
                'verbose_name_plural': 'Peak Generation Events',
            },
        ),
        migrations.CreateModel(
            name='WindEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='WARNING', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_persistent', models.BooleanField(default=True)),
                ('event_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wind_records', to='calculator.systemeventmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wind system event',
                'verbose_name_plural': 'Wind System Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='peakeventmodel',
            name='daily_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peak_records', to='calculator.systemeventmodel'),
        ),
        migrations.AddField(
            model_name='systemeventmodel',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='systemeventmodel',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='systemeventmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

    ]
