# Generated by Django 5.2.7 on 2026-07-25 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0045_alter_systemeventmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='peakeventmodel',
            constraint=models.UniqueConstraint(fields=('daily_event', 'user', 'peak_hour', 'status'), name='unique_peak_event_per_user_day'),
        ),
    ]
