# Generated by Django 5.2.7 on 2026-07-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0046_peakeventmodel_unique_peak_event_per_user_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='windeventmodel',
            name='gust_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='windeventmodel',
            name='wind_direction',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='windeventmodel',
            name='wind_strength',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
