# Generated by Django 5.2.7 on 2026-07-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0047_windeventmodel_gust_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='windeventmodel',
            name='wind_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
