# Generated by Django 5.2.7 on 2026-07-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0048_windeventmodel_wind_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windeventmodel',
            old_name='wind_time',
            new_name='event_time',
        ),
    ]
