# Generated by Django 5.2.7 on 2026-08-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0049_rename_wind_time_windeventmodel_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentrylinemodel',
            name='weather_scores',
            field=models.JSONField(blank=True, default=dict, verbose_name='Weather score'),
        ),
    ]
