# Generated by Django 5.2.7 on 2026-08-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0050_dataentrylinemodel_weather_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilesettingsmodel',
            name='is_automatic_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofilesettingsmodel',
            name='license_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
