# Generated by Django 5.2.7 on 2026-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0051_userprofilesettingsmodel_is_automatic_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilesettingsmodel',
            name='receive_data_method',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20),
        ),
    ]
