# Generated by Django 5.2.7 on 2026-08-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0052_userprofilesettingsmodel_receive_data_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelsarraymodel',
            name='peak_power_kwp',
        ),
        migrations.AddField(
            model_name='panelsarraymodel',
            name='peak_power_wh',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Peak power (Wp)'),
        ),
    ]
