# Generated by Django 5.2.7 on 2026-08-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0053_remove_panelsarraymodel_peak_power_kwp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelsarraymodel',
            name='peak_power_wh',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Peak power (Wp)'),
        ),
    ]
