# Generated by Django 5.2.7 on 2026-08-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0054_alter_panelsarraymodel_peak_power_wh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemMessage',
        ),
    ]
