# Generated by Django 5.2.7 on 2026-08-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0055_delete_systemmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemeventmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='systemeventmodel',
            name='event_timestamp',
        ),
        migrations.RemoveField(
            model_name='systemeventmodel',
            name='is_persistent',
        ),
        migrations.RemoveField(
            model_name='systemeventmodel',
            name='level',
        ),
        migrations.RemoveField(
            model_name='systemeventmodel',
            name='message',
        ),
        migrations.RemoveField(
            model_name='systemeventmodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='systemeventmodel',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
