# Generated by Django 5.2.7 on 2026-08-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0057_systemmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemeventmodel',
            name='category',
        ),
    ]
