# Generated by Django 5.2.7 on 2025-11-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_dataentrylinemodel_full_day_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='afternoon_data_charge',
            field=models.IntegerField(blank=True, verbose_name='Денний рівень заряду'),
        ),
        migrations.AlterField(
            model_name='dataentrylinemodel',
            name='afternoon_data_price',
            field=models.FloatField(blank=True, verbose_name='Вартість використаної енергії на день'),
        ),
    ]
