# Generated by Django 5.2.7 on 2025-12-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_currenttariffmodel_alter_dataentrylinemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataentrylinemodel',
            name='weather',
        ),
        migrations.AddField(
            model_name='dataentrylinemodel',
            name='weather',
            field=models.ManyToManyField(db_index=True, related_name='weather', to='calculator.weathercondition', verbose_name='Погода'),
        ),
    ]
