# Generated by Django 3.2.25 on 2026-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('source_code', models.TextField()),
                ('live_preview', models.TextField()),
            ],
            options={
                'verbose_name': 'project item',
                'verbose_name_plural': 'Project Items',
            },
        ),
    ]
