# Generated by Django 3.2.25 on 2026-05-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_contactmessagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessagemodel',
            old_name='body',
            new_name='mail_body',
        ),
        migrations.RenameField(
            model_name='contactmessagemodel',
            old_name='subject',
            new_name='project_theme',
        ),
        migrations.RenameField(
            model_name='contactmessagemodel',
            old_name='sender_email',
            new_name='subject_email',
        ),
        migrations.RenameField(
            model_name='contactmessagemodel',
            old_name='sender_name',
            new_name='subject_name',
        ),
    ]
