# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 3.2.25 on 2026-05-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_rename_contactmessagemodel_inboundmessagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmessagemodel',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inboundmessagemodel',
            name='is_replead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboundmessagemodel',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='inboundmessagemodel',
            index=models.Index(fields=['subject_email', 'is_archived'], name='personal_in_subject_d37eb1_idx'),
        ),
    ]
