# SPDX-License-Identifier: AGPL-3.0-or-later
# Generated by Django 3.2.25 on 2026-05-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20260511_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboundmessagemodel',
            old_name='is_replead',
            new_name='is_replied',
        ),
    ]
