# Generated by Django 5.2.7 on 2026-05-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_rename_is_replead_inboundmessagemodel_is_replied'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboundmessagemodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'contact message', 'verbose_name_plural': 'Contact Messages'},
        ),
    ]
